spring:
 cloud:
   gateway:
     routes:
       - id: blog-service
         uri: lb://BLOG-SERVICE
         predicates:
           - Path=/blogs/**
         filters:
           - AuthenticationFilter


       - id: authentication
         uri: lb://AUTHENTICATION
         predicates:
           - Path=/auth/**

       - id: profile-service
         uri: lb://PROFILE-SERVICE
         predicates:
           - Path=/profile/**  
         filters:
           - AuthenticationFilter
           
       - id: media-service
         uri: lb://MEDIA-SERVICE
         predicates:
           - Path=/media/**  

       - id: like-service
         uri: lb://LIKE-SERVICE
         predicates:
           - Path=/likes/** 
         filters:
           - AuthenticationFilter

 application:
   name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka


