spring:
 cloud:
   gateway:
     routes:
       - id: blog-service
         uri: lb://BLOG-SERVICE
         predicates:
           - Path=/blogs/**
         filters:
           - AuthenticationFilter


       - id: authentication
         uri: lb://AUTHENTICATION
         predicates:
           - Path=/auth/**

 application:
   name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka


