server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://mysql-23942956-neerajmanivarnan-001.a.aivencloud.com:20164/mediatest
    username: avnadmin
    password: AVNS_6R4qVtdTKPKzZlsmoqP
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
  

gcp:
  config:
    file: gcp-account-file.json
  project:
    id: imposing-pipe-356718
  bucket:
    id: media-bucket-007
  dir:
    name: dev

logging:
  level:
    org.springframework: ERROR
    com.app: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
