version: '3.7'

services:
  eureka-server:
    image: neergasm/eureka-server:0.1 # Replace with your preferred Eureka Server image
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker  # Set profile for Eureka Server
    restart: always
    networks:
      - tkmtube-network

  api-gateway:
    image: neergasm/api-gateway:0.1
    ports:
      - "8000:8000"  # Adjust port if needed
    environment:
      - SPRING_PROFILES_ACTIVE=docker  # Set profile for API Gateway
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server  # Eureka server discovery URL
    depends_on:
      - eureka-server
    networks:
      - tkmtube-network

  blog-service:
    image: neergasm/blog-service:0.6  # Replace with path to your blog service Dockerfile
    ports:
      - "8080:8080"  # Adjust port if needed
    environment:
      - SPRING_PROFILES_ACTIVE=docker  # Set profile for blog service
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server
      - API_GATEWAY_SERVICE_URL=http://api-gateway
    depends_on:
      - eureka-server
      - api-gateway
    networks:
      - tkmtube-network

  user-details:
    image: neergasm/user-details:0.1  # Replace with path to your blog service Dockerfile
    ports:
      - "9000:9000"  # Adjust port if needed
    environment:
      - SPRING_PROFILES_ACTIVE=docker  # Set profile for blog service
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server  # Eureka server discovery URL
      - API_GATEWAY_SERVICE_URL=http://api-gateway
    depends_on:
      - eureka-server
      - api-gateway
    networks:
      - tkmtube-network


networks:
  tkmtube-network:
